# Generated by Django 3.1.1 on 2020-10-23 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0002_auto_20201021_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namecard_tbl',
            name='birth_dt',
        ),
    ]
