# Generated by Django 3.1.1 on 2020-10-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth_dt',
        ),
        migrations.AddField(
            model_name='student',
            name='add_dt',
            field=models.DateField(null=True, verbose_name='ADD'),
        ),
    ]
