# Generated by Django 3.1.1 on 2020-10-30 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj', models.CharField(max_length=30, verbose_name='SUBJ')),
            ],
            options={
                'ordering': ('subj',),
            },
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='NAME')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sugang.subject')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
